-- Seed passages + questions from local original content.
-- Generated by scripts/generate-seed.ts — do not hand-edit; regenerate instead.
-- Requires migration 20260905143000_phase06_foundation.sql applied first.

begin;

delete from public.questions;
delete from public.passages;

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'The Unfinished Song',
  'A waiter can hold a dozen orders in his head at once. He knows table four wants the fish, that table nine has changed its mind twice, and that someone near the window is still deciding. Then the plates go out, the bill is paid, and the whole arrangement vanishes from his memory within minutes.

In the 1920s a researcher noticed this pattern and decided to test it. She asked people to work through a series of small tasks: puzzles, arithmetic, simple crafts. Some they were allowed to finish. Others were interrupted partway through. Later she asked them to recall as many of the tasks as they could.

The interrupted ones came back far more easily. Unfinished work seemed to stay awake in the mind, tapping quietly for attention, while completed work went silent.

The effect explains more than laboratory puzzles. It is why a song cut off mid-chorus loops in your head all afternoon, and why a conversation that ended badly replays itself at two in the morning. Closure is not only emotionally satisfying. It is a filing instruction. Without it the mind keeps the folder open on the desk, refusing to put it away.

Which is also why starting is often the hardest part, and stopping is the second hardest. Once a thing has been opened, some part of you insists on closing it.',
  'psychology'::public.category,
  'easy'::public.difficulty,
  226
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '8748e8c9-7036-4e5a-af8d-81863b1ba29b'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'What is the central claim of the passage?',
  ARRAY['Unfinished things stay active in the mind while finished ones fade', 'Interruption improves the quality of work', 'Memory declines steadily throughout the day', 'Waiters have unusually strong memories']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '8196db06-1e8a-438c-a8a8-a4152d9594f4'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'What did the researcher do differently with some of the tasks?',
  ARRAY['She asked people to repeat them twice', 'She interrupted them partway through', 'She made them much harder', 'She removed the time limit']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0b3de664-8906-4c99-a0c3-2651a2460af5'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'Which kinds of tasks did the researcher use?',
  ARRAY['Memory drills and word lists', 'Physical exercises', 'Puzzles, arithmetic and simple crafts', 'Written essays']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e9c8d4eb-38a2-46aa-a0b5-3cb1d0c97c18'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'When did the research described take place?',
  ARRAY['The 1890s', 'The 1920s', 'The 1950s', 'The 1970s']::text[],
  1,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '66939dc8-27c1-4f27-afdd-0a80dbc11932'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'In the waiter example, when does the order vanish from memory?',
  ARRAY['After the plates go out and the bill is paid', 'Only at the end of the working day', 'As soon as the order is taken', 'While the food is being prepared']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0570b6f9-3871-4dae-a12c-f7ba31a6b84b'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'The passage calls closure "a filing instruction". This means closure mainly works as',
  ARRAY['a reward the mind gives itself', 'a signal that memory can put something away', 'a way of storing detail permanently', 'a method for organising future tasks']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '39c84096-5410-4d6a-a18a-89c980cef90e'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'Based on the passage, why might a song cut off mid-chorus keep repeating in your head?',
  ARRAY['Because the interruption makes it seem more important', 'Because music is stored differently from words', 'Because the mind treats it as unfinished and keeps it open', 'Because familiar melodies are easier to recall']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '4a89e363-0e7d-46c6-a8ff-5b49005ccb4d'::uuid,
  'c492b46b-009f-4dfa-aea3-50328654832b'::uuid,
  'What does the final line suggest about why stopping is difficult?',
  ARRAY['Habits are harder to break than to form', 'People overestimate how long tasks will take', 'Effort already spent makes quitting feel wasteful', 'Something opened creates a pull towards closing it']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'What the Roots Are Saying',
  'Walk into an old forest and you will be told, quite confidently, that you are looking at individual trees. You are not. You are looking at the visible tips of a negotiation that has been running underground for millions of years.

Beneath the soil, fungal threads thinner than a hair wrap themselves around and inside tree roots. The fungus cannot make its own sugar, so it takes some from the tree. In exchange it reaches into the soil far more finely than any root could, pulling up water, phosphorus and nitrogen and handing them over.

Because a single fungal network can connect many trees at once, these trades do not stay private. Sugar moves from a tree standing in full sunlight to a seedling stuck in shade. Chemical warnings about insect attacks travel from a chewed tree to its neighbours, which begin producing bitter defensive compounds before the insects ever reach them.

It is tempting to call this cooperation, and some of it is. But the fungus is not a charity. It bargains, it favours the trees that pay best, and it has been caught keeping more than its share.

What looks like a peaceful wood is closer to a crowded marketplace. One that happens to be entirely silent, entirely dark, and directly beneath your boots.',
  'nature'::public.category,
  'easy'::public.difficulty,
  216
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c5f00fb7-db40-48e9-a0d2-f317395367e2'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'What is the passage mainly arguing?',
  ARRAY['Trees are linked by an underground network of trade', 'Old forests recover from insect damage quickly', 'Forests are healthier when trees grow far apart', 'Fungi are the most important organisms in a forest']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0419b5f8-6f40-49f1-a174-5a88409a3d9d'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'What does the fungus receive from the tree?',
  ARRAY['Water', 'Sugar', 'Phosphorus', 'Nitrogen']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '10ee4498-2a5d-4e9f-a686-d24f63f24190'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'What does the fungus supply in return?',
  ARRAY['Carbon dioxide', 'Structural support for the roots', 'Water, phosphorus and nitrogen', 'Sunlight and warmth']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '5546ef18-a7d3-447a-ac4f-200459f66aee'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'How does the passage describe the size of the fungal threads?',
  ARRAY['Visible only in clusters', 'About the width of a seed', 'Thicker than a root tip', 'Thinner than a hair']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '8033cd47-5a21-4b49-a45b-b141febff0a9'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'According to the passage, when do neighbouring trees start producing defensive compounds?',
  ARRAY['Before the insects reach them', 'At the end of the growing season', 'Once the fungal network dies back', 'Only after they are chewed themselves']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'd98b600f-0949-4eb1-a7fd-b20bebf8555f'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'The passage says the fungus "is not a charity". This is meant to convey that it',
  ARRAY['gives without expecting anything back', 'trades on terms that favour itself', 'cannot survive without a host', 'harms the trees it connects']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e1c9704c-7e9c-4efc-a6d8-029023f07a99'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'Why does sugar move to a seedling stuck in shade?',
  ARRAY['Older trees deliberately protect their offspring', 'The fungus cannot store sugar for long', 'The shaded seedling cannot make enough of its own', 'Shaded soil holds more nutrients']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '6035e901-145d-4625-a2ab-92a75fcc2747'::uuid,
  '0cb711b6-6b03-4b49-afd1-59e22108630b'::uuid,
  'What does the marketplace comparison suggest about the forest?',
  ARRAY['It is too complex to study directly', 'It collapses when one species dominates', 'It is fundamentally cooperative and harmonious', 'It is driven by exchange and self-interest as well as sharing']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'The Lighthouse Keeper''s Inventory',
  'Every Sunday, Mara counted what the sea had given her. She kept the list in a ledger her predecessor had left behind, and she wrote in the same cramped hand he had used, though she had never met him.

Week eleven: one boot, left foot, size unknown. A crate lid stamped with a word in a language she did not read. Forty-three metres of blue rope, which she coiled and hung beside the door, because rope was always worth keeping.

Week nineteen: a child''s shoe. She wrote it down, and then she sat for a while with the pen in her hand, and then she wrote beneath it, nothing else came ashore, which was true.

The lamp above her turned and turned. Ships passed and did not stop, because that was the entire point of her. Success, in her profession, looked exactly like nothing happening at all.

In the spring she finally read the ledger''s first page, which she had never bothered with. Week one, in that same cramped hand: began keeping this so someone would know I was here.',
  'fiction'::public.category,
  'easy'::public.difficulty,
  180
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '7b1613c0-19a5-40e1-a580-f68241e7895b'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'What is the story mainly about?',
  ARRAY['A solitary keeper recording what the sea leaves behind', 'A dispute over who owns salvaged cargo', 'The closing of an old lighthouse', 'A keeper rescuing survivors from a wreck']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e8c5eeab-5fad-4f37-a1bd-d6935d20e5ae'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'What does Mara record in the ledger?',
  ARRAY['The ships that pass the lighthouse', 'Items that wash ashore', 'Repairs made to the lamp', 'The weather each Sunday']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e6630b77-2f63-402d-a099-c89930840e11'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'Why does Mara keep the blue rope?',
  ARRAY['It matches the lamp housing', 'She plans to return it to its owner', 'Rope is always worth keeping', 'It was the only item she could carry']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '1cf5c1d1-8730-4f7e-af02-22837ce4615f'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'How long was the rope she found?',
  ARRAY['Fourteen metres', 'Thirty metres', 'Forty-three metres', 'Sixty metres']::text[],
  2,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'df1b39ab-4714-47b6-adc8-b11ce1f1977c'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'When does Mara finally read the first page of the ledger?',
  ARRAY['In the spring', 'Just before she leaves the post', 'On the day she arrives', 'In week nineteen']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '89a539f5-1d31-4ac0-a9ca-d1909b84f446'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'What does "Success, in her profession, looked exactly like nothing happening at all" mean?',
  ARRAY['Her work went unnoticed by her employers', 'Doing the job well meant no wrecks occurred', 'She had very little to do most weeks', 'The lighthouse was no longer necessary']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0f89ee68-350c-4ebe-a3de-c04f515c1fb4'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'Why does Mara pause with the pen after writing about the shoe?',
  ARRAY['She is unsure how to describe it', 'She is deciding whether to keep it', 'She understands what it implies and does not write it', 'She is waiting for the lamp to turn']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '45abcc63-1eb1-4fc3-a46f-4a1c375553fd'::uuid,
  '06cdaf06-cfa3-4070-abe3-d6b56a4d070d'::uuid,
  'What does the final line reveal about the ledger?',
  ARRAY['It was required by the lighthouse authority', 'It was intended as a guide for future keepers', 'It had been abandoned halfway through', 'It began as a record kept against being forgotten']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'The Cost of Remembering',
  'A photograph you take today will probably outlive you, but not for the reason you would like. It will not survive because it is precious. It will survive because deleting it is more trouble than keeping it.

Storage has become so cheap that the economics of forgetting have inverted. For most of human history, remembering was the expensive act. Clay had to be fired, parchment scraped and reused, ledgers copied by hand in rooms full of people paid to copy ledgers. Anything preserved had to earn its place. Now the opposite holds. Keeping everything costs less than the labour of deciding what to throw away.

The cost has not disappeared, though. It has moved. Somewhere there is a building the size of several football pitches, drawing as much electricity as a small town, filled with drives that spin so that a photograph of a lunch you have entirely forgotten can be retrieved in under a second.

Those buildings need cooling, and cooling needs water. They need replacement hardware on a rolling schedule, because drives fail predictably enough that the whole system is designed around their failure rather than their reliability. Every file is written more than once, in more than one place, so that no single failure matters to anyone.

So the true price of a casual photograph is not the megabytes. It is a share of a cooling system, a share of a power contract, and a share of the redundant copies made on your behalf without your knowledge.

None of this is an argument for deleting your photographs. It is an argument for noticing that the cloud is a weather metaphor bolted onto some of the heaviest infrastructure our species has ever built.',
  'technology'::public.category,
  'medium'::public.difficulty,
  285
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '25b2a46a-07b4-4dd3-a4c3-8cef6779aba8'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'What is the passage mainly arguing?',
  ARRAY['Cheap storage hides a large physical cost that has simply moved', 'Photographs are less valuable than they used to be', 'Data centres will soon become too expensive to run', 'People should delete more of what they store']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '627930aa-6846-43ef-af09-b94f0d76ca9a'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'Why is every file written more than once?',
  ARRAY['To satisfy legal requirements', 'Because the system is designed around predictable drive failure', 'Because compression is unreliable', 'To speed up retrieval times']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '33c5c174-0b58-4e20-a98f-dc4ced3d27d8'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'Besides electricity, what resource does the passage say cooling requires?',
  ARRAY['Rare earth metals', 'Diesel fuel', 'Water', 'Compressed air']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '250ff986-78d8-4443-a5a6-dc599d7e1b0a'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'How does the passage describe the electricity a storage building draws?',
  ARRAY['As much as a large city', 'As much as a passenger aircraft', 'As much as a single street', 'As much as a small town']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'fa3da771-f67b-4fee-a91b-64219728f5c8'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'According to the passage, what was true for most of human history, before the inversion?',
  ARRAY['Preserving anything was expensive, so it had to earn its place', 'Most societies deliberately destroyed their records', 'Copying was cheap but storage was scarce', 'Records were kept by machines rather than people']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'ee55e811-f567-43b1-aeff-68c6c9c9346c'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'What does the passage mean by "the economics of forgetting have inverted"?',
  ARRAY['Storage prices now rise rather than fall', 'Keeping everything is now cheaper than sorting through it', 'Memory is valued less than it once was', 'Forgetting has become socially unacceptable']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '6d135221-acbc-4547-a11b-3fe1d889b983'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'Why does the passage mention parchment being scraped and reused?',
  ARRAY['To explain why so few ancient documents survive', 'To show how fragile early records were', 'To illustrate that storage itself was once costly enough to force reuse', 'To argue that handwriting preserved information better']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'fefa8cc2-1b93-443a-a5a3-ebd3c693c476'::uuid,
  '9e4d06d4-3f2a-48fc-a276-e54111ed1648'::uuid,
  'What is the point of calling the cloud "a weather metaphor"?',
  ARRAY['It implies the term was chosen by engineers', 'It suggests storage is unpredictable', 'It hints that data is constantly moving', 'It highlights how a light word conceals heavy physical infrastructure']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'The Box That Shrank the World',
  'Before the middle of the twentieth century, loading a ship was a craft. Dockworkers moved barrels, sacks and crates by hand and by hook, fitting awkward shapes against one another like a puzzle that had to be solved fresh at every port.

It was slow in a way that is hard to imagine now. Cargo could spend longer sitting on a dock than it spent crossing an ocean. Theft was constant and more or less expected, since goods passed through many hands in the open. The cost of moving something was dominated not by the voyage but by the loading.

The idea that changed this was not really a technology. Steel boxes are not difficult to manufacture. The difficulty was agreement. For the box to work it had to be the same size everywhere: the same size on a truck in one country, on a train in another, and on a crane owned by a competitor.

That kind of standardisation is expensive in a way engineering is not. Ports had to be rebuilt around cranes rather than gangs of workers. Ships had to be redesigned as floating shelves. Unions had to negotiate over jobs everyone knew were disappearing. Firms had to adopt dimensions chosen by rivals.

When it finally settled, the cost of moving goods collapsed. And when shipping becomes nearly free relative to the value of what is shipped, it stops being a factor in deciding where things are made. Factories drift toward cheap labour, components cross oceans several times before assembly, and a product stops having a single country of origin.

The box did not simply move cargo more efficiently. It quietly rearranged the map of who makes what for whom.',
  'business'::public.category,
  'medium'::public.difficulty,
  283
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'dc7ba939-e41c-4ec5-ae52-a55fa0ba6f2b'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'What is the central point of the passage?',
  ARRAY['Standardising the shipping container reshaped global manufacturing', 'Dockworkers resisted mechanisation and lost', 'Theft was the main problem in early shipping', 'Containers made ships faster at sea']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '67662324-38a6-4685-ae45-3fe5cd666639'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'What was the main obstacle to containerisation?',
  ARRAY['Manufacturing steel boxes cheaply', 'Getting everyone to agree on a single standard', 'Building ships large enough', 'Finding ports deep enough for the new ships']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '71535058-7d01-4899-a92d-024947b28ead'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'What dominated the cost of moving goods before containers?',
  ARRAY['Insurance against storms', 'Port fees and tariffs', 'The loading and unloading', 'Fuel for the voyage']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'cc7d8ffe-ac4a-4bf5-aa2f-02d275aacc3c'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'How does the passage describe cargo timing before containers?',
  ARRAY['It was usually loaded within a single day', 'It spent most of its journey in customs', 'It moved faster than modern freight over short routes', 'It could sit on a dock longer than it spent crossing an ocean']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '8a636528-5520-4ee2-a261-6afe0099d3cd'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'According to the passage, what had to happen before shipping costs collapsed?',
  ARRAY['Ports, ships and labour agreements all had to be rebuilt around a common standard', 'Ocean freight had to be deregulated internationally', 'Factories had to relocate to coastal regions', 'Cranes had to become cheap enough for small ports']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '440fc135-9310-4179-a3d7-9c3b8298359a'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'Ships being "redesigned as floating shelves" suggests they became',
  ARRAY['lighter and faster over long distances', 'structured to hold uniform boxes in stacked slots', 'capable of carrying passengers as well as freight', 'easier to repair in any port']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '7b472b32-e6a6-43f9-a78b-e6d8672e13ba'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'Why does the passage say standardisation is expensive "in a way engineering is not"?',
  ARRAY['Engineers are paid more than administrators', 'Steel prices rise when demand is coordinated', 'The cost lies in rebuilding institutions and habits, not in making the object', 'Standards require constant revision']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '7d019276-139e-424b-a1e8-bf44d9807200'::uuid,
  '54af4d21-d82a-491d-ad58-02566fc46b68'::uuid,
  'Why does cheap shipping lead factories to move toward cheap labour?',
  ARRAY['Governments subsidise coastal manufacturing', 'Components are too fragile to travel far otherwise', 'Cheap labour regions have better ports', 'Distance stops being a meaningful cost in the decision']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'The Salt Roads',
  'It is difficult now to take salt seriously. It sits on the table in a shaker that nobody guards. For most of recorded history it was closer to a strategic resource, because salt was not a seasoning first. It was the only reliable way to keep food from rotting.

A society that could preserve fish and meat could store surplus, feed an army on the move, and survive a bad winter. A society that could not was permanently at the mercy of the harvest. That single fact turned a common mineral into something worth crossing deserts for.

Caravans moved slabs of it south across the Sahara, trading with kingdoms that had gold but no salt, and returning with gold from kingdoms that had salt but no gold. Both sides walked away convinced they had cheated the other, which is usually the sign of a trade that will continue.

Governments noticed. A commodity that every household must buy, in roughly predictable quantities, regardless of income, is close to a perfect object of taxation. Salt taxes funded states across Europe and Asia for centuries, and they were resented with a consistency that few other taxes have achieved.

That resentment had teeth. Salt levies helped provoke unrest in pre-revolutionary France, and centuries later a colonial salt monopoly in India was challenged by a march to the sea specifically because the tax touched everyone, including the poorest.

The pattern is worth remembering. What a society taxes reveals what it thinks nobody can refuse.',
  'history'::public.category,
  'medium'::public.difficulty,
  249
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c504b51e-d313-48a2-aee3-1a7dac0212bc'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'What is the passage mainly about?',
  ARRAY['Why a common mineral became strategically and politically powerful', 'The decline of the Saharan trade routes', 'How diets changed after refrigeration', 'How salt was discovered and refined']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e685e11b-19ae-40d0-aaf5-846a096c3387'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'Why did salt matter so much historically?',
  ARRAY['It was rare in most regions', 'It was the main way to preserve food', 'It was used as currency everywhere', 'It was required for metalworking']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c6ba3542-e6d8-417d-a9e5-1aede0aeff1b'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'What was traded across the Sahara according to the passage?',
  ARRAY['Gold for horses', 'Salt for textiles', 'Salt for gold', 'Salt for grain']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'a0f63342-8936-45f4-ac87-5a8e1d8b984b'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'Which two examples of resistance to salt taxes does the passage give?',
  ARRAY['Spain and the Netherlands', 'China and Japan', 'Rome and Egypt', 'Pre-revolutionary France and colonial India']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e717333a-6317-4f87-af49-0b59b2f6f5b4'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'In the passage, what follows from a society being able to preserve fish and meat?',
  ARRAY['It can store surplus, supply armies and survive bad winters', 'It becomes dependent on imports', 'It grows faster than its neighbours in population', 'It abandons farming for trade']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'bf130b7d-3300-4561-aff5-51c67536233d'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'Calling salt "a strategic resource" implies that it was',
  ARRAY['valued mainly for its rarity', 'essential to a state''s security and survival', 'controlled entirely by merchants', 'traded only in times of war']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '52ff367c-d1ad-4fd0-a043-1819e6d6ac3a'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'Why does the passage say both sides believed they had cheated the other?',
  ARRAY['The caravans concealed the true quantities', 'Gold was deliberately overvalued by traders', 'Each side valued what it lacked more highly than what it had', 'Neither side understood the exchange rate']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '5fdcd942-1bf0-46e6-a309-3d4118c4e82f'::uuid,
  '0680e9b4-1164-41be-a072-76333200ea12'::uuid,
  'What does the closing line suggest about taxation in general?',
  ARRAY['Taxation always provokes rebellion eventually', 'Tax policy follows trade routes', 'Taxes are usually placed on luxuries', 'Governments tax what people cannot do without']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'Small Things That Refuse to Die',
  'The tardigrade is about half a millimetre long, walks on eight stubby legs, and lives in the water film clinging to moss and lichen. It is also the animal most often described, with some exaggeration, as indestructible.

The reputation rests on a single trick. When its environment dries out, a tardigrade does not attempt to survive the drought as a functioning animal. It stops being one. It pulls in its legs, contracts into a barrel shape, and expels almost all of the water in its body. Metabolism drops to a level that is difficult to distinguish from zero. This suspended condition is called cryptobiosis, and an animal in it is neither quite alive nor dead in any sense the words were built for.

The chemistry is the interesting part. Water is not simply lost; it is replaced. The animal floods its cells with protective sugars and disordered proteins that harden into a glass-like matrix. Delicate structures that would normally collapse without water are instead locked in place, held rigid by this internal glass until liquid returns. Nothing moves, so nothing breaks.

In that state a tardigrade tolerates conditions that have nothing to do with its natural habitat: temperatures near absolute zero, pressures far beyond the deep ocean, radiation doses that would be lethal to us hundreds of times over. Some have been revived after exposure to the vacuum of space. Their genomes carry proteins that appear to shield DNA from radiation damage, and repair machinery that is unusually good at reassembling broken strands.

The exaggeration is worth correcting, though. An active, hydrated tardigrade is a fairly ordinary small animal. It can be crushed, eaten, boiled or starved. Its resilience is not a property of the creature so much as a property of a state it can enter, and only when it is given enough warning to prepare.

Which is a reasonable description of most durability. Very little survives everything. A great deal survives more than expected, provided it can stop in time.',
  'science'::public.category,
  'hard'::public.difficulty,
  332
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '341fab94-996b-4be0-a056-6bcf17a89381'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'What is the central argument of the passage?',
  ARRAY['Their resilience belongs to a state they enter, not to the animal itself', 'Extreme environments select for smaller organisms', 'Cryptobiosis could be reproduced in human cells', 'Tardigrades are the toughest animals on Earth']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'b55dae5b-cb6c-40f8-a26f-3fe321028da0'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'What is cryptobiosis, as described in the passage?',
  ARRAY['A rapid reproductive cycle triggered by drought', 'A suspended state with metabolism near zero', 'A protective outer shell the animal grows', 'A form of hibernation lasting one season']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '236e6200-64f4-472f-a8a4-c9d2adba8c4c'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'What does the tardigrade replace the water in its cells with?',
  ARRAY['A salt solution', 'Air pockets', 'Sugars and proteins that form a glass-like matrix', 'A waxy lipid layer']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '43f0f1f7-a277-467e-ab96-fba914555aa4'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'Where does the tardigrade normally live?',
  ARRAY['In glacial ice', 'In deep ocean sediment', 'Inside the roots of desert plants', 'In the water film on moss and lichen']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'f84f1e38-4e4d-4a07-a795-77c23a0107b6'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'What happens first when the environment dries out?',
  ARRAY['The animal pulls in its legs and contracts into a barrel shape', 'Its DNA repair machinery activates', 'It seeks out a new source of water', 'Its outer cuticle thickens']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c823daf6-1968-41de-a3ce-2728b58a6ff2'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'In "Nothing moves, so nothing breaks", what is the writer explaining?',
  ARRAY['Why the animal cannot be revived once frozen', 'Why rigidity protects structures that would otherwise collapse', 'Why metabolism must stop entirely', 'Why the glass matrix eventually dissolves']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c381ba57-a9ee-4160-aca1-21d317c2cda9'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'Why does the passage call the tardigrade''s reputation exaggerated?',
  ARRAY['Only a few species can enter the state', 'The revivals were never independently confirmed', 'An active, hydrated tardigrade is quite ordinary and vulnerable', 'The animal dies shortly after being revived']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '2d97cd6a-463d-432f-aaf0-f90aac9c4396'::uuid,
  'bc47f8bf-0167-46c2-af3b-b6683eadcf55'::uuid,
  'What broader claim does the final paragraph make about durability?',
  ARRAY['Nothing can be truly destroyed, only transformed', 'Small things endure better than large ones', 'Preparation matters less than genetics', 'Survival depends on being able to stop in time']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'Punctuation for Feelings',
  'Speech carries far more than words. Pitch rises and tone flattens, a pause lands in the wrong place, an eyebrow moves. Linguists estimate that a substantial share of what we understand in conversation arrives through channels that have nothing to do with vocabulary.

Writing threw all of that away, and for centuries the loss barely mattered. Written language was mostly formal, asynchronous and edited. Letters, contracts and books do not need to convey the exact emotional temperature of a sentence, because nobody expects a reply within nine seconds.

Text messaging broke that arrangement. It is written language performing the job of speech: fast, casual, back and forth, between people who know each other. And it arrived without any of the equipment speech uses to signal warmth, irony or hesitation.

So users built the equipment themselves, quickly and without permission. Repeated letters stretch a word the way a voice would. Lowercase signals ease; full capitals signal volume or panic. The ellipsis became a marker of reluctance. Most strikingly, the full stop acquired a tone. In a short message, a sentence ending in a period now reads to many younger readers as cold or final, because in a medium where the line break already ends the thought, choosing to add a period is choosing to add something.

Emoji fit this pattern rather than breaking it. They are usually described as decoration, but they mostly behave grammatically. A smiling face at the end of a blunt request does not add a picture of a face; it does the work an apologetic smile does in person, softening the sentence it is attached to. Its position matters, it modifies rather than replaces, and using it wrongly reads as strange rather than merely ugly.

What looks like the decline of written language is closer to the opposite. Writing lost the body when it was invented, and having suddenly been asked to do the body''s job, it is growing the missing organs in public, at speed, in front of everyone.',
  'culture'::public.category,
  'hard'::public.difficulty,
  333
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '9d5388f1-b9e1-41e3-abfe-45ed8be0c267'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'What is the passage mainly arguing?',
  ARRAY['Written language is inventing new tools to carry tone', 'Emoji will eventually replace punctuation', 'Speech is a more efficient medium than writing', 'Digital writing is eroding grammatical standards']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '8eaaa81e-0d45-4a67-aaa3-f06441ed499f'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'Why did the loss of tone in writing not matter for centuries?',
  ARRAY['Most people could not read', 'Written language was formal, edited and asynchronous', 'Letters included detailed descriptions of feeling', 'Writing was mostly read aloud by a speaker']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '6b152590-4ed4-46fa-a308-1eaf8363b5a5'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'What does the passage say lowercase signals?',
  ARRAY['Formality', 'Urgency', 'Ease', 'Reluctance']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c57e713e-5dfa-4e4c-aa73-85b9e75a0c57'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'Which marker does the passage associate with reluctance?',
  ARRAY['The exclamation mark', 'Repeated letters', 'Full capitals', 'The ellipsis']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '05141573-dd0e-4172-a7de-262d90cc7570'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'According to the passage, what changed the arrangement that had held for centuries?',
  ARRAY['The arrival of fast, casual text messaging', 'The standardisation of punctuation', 'The invention of the keyboard', 'The spread of printed books']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '2d1a599d-f905-4143-a674-101454e77458'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'When the passage says emoji "modify rather than replace", it means they',
  ARRAY['stand in for words the writer cannot spell', 'adjust the tone of the sentence they attach to', 'are optional decoration at the end of a message', 'change meaning depending on the device used']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '063d3448-badc-484b-a56e-d8ee271feff7'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'Why does a full stop now read as cold in short messages?',
  ARRAY['It suggests the writer is in a hurry', 'It was traditionally used only in formal writing', 'The line break already ends the thought, so adding it adds meaning', 'Autocorrect rarely inserts one']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e090add7-3512-48f7-a85d-7111fca7877d'::uuid,
  '91791101-e344-4e79-a79a-d12fe7fc6691'::uuid,
  'What does the image of writing "growing the missing organs" imply?',
  ARRAY['New conventions are imposed by platforms rather than users', 'Written and spoken language are merging completely', 'The change is unnatural and likely to be reversed', 'Writing is developing in public what speech always had']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'The Cartographers'' Blank Spaces',
  'A map is usually read as a statement of fact, which is exactly what makes it such an effective argument. Every map is a set of decisions about what counts as real, what deserves a name, and what can be left out without complaint.

The blank spaces are the most revealing part. On early maps, unmapped regions were often filled with decorative flourishes, invented coastlines or speculative interiors. The familiar phrase about dragons is largely a modern myth; it survives on almost no historical maps. But the impulse behind the story is accurate. Emptiness was uncomfortable, and mapmakers filled it, sometimes with ornament and sometimes with guesses that hardened into accepted geography once they had been copied a few times.

Later, blankness became a deliberate technique rather than an embarrassment. As European powers expanded, interiors that had been confidently, if inaccurately, drawn were quietly emptied. Territory that was inhabited, farmed and governed appeared on the paper as unmarked space awaiting survey. A blank interior is an invitation. It implies that nothing there has yet been claimed, and therefore that a claim is available.

The same logic operates through naming. To place a name on a feature that already had several is not to record it but to overwrite it, and the overwriting travels: the printed name enters treaties, then schoolbooks, then ordinary speech, until the earlier names sound like local colour rather than the original record.

None of this requires a conspiracy. Mapmakers work from the sources they trust, and the sources they trust are the ones produced by the institutions paying for the map. The distortion is structural rather than deliberate, which is precisely why it is so durable.

Reading an old map well means asking two questions at once. What was known, and what was it useful to appear not to know?',
  'history'::public.category,
  'hard'::public.difficulty,
  304
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '4b6c40b0-72ed-47b6-a506-524c223999fd'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'What is the passage mainly arguing?',
  ARRAY['Maps make arguments about ownership while appearing to state facts', 'Cartography improved once surveying became systematic', 'Naming conventions vary widely between empires', 'Early maps were less accurate than we assume']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '9826374f-4a9d-48d0-a55a-087dc105f424'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'What does the passage say about the phrase concerning dragons?',
  ARRAY['It appeared on most medieval maps', 'It is largely a modern myth found on almost no historical maps', 'It was a coded warning about pirates', 'It marked areas with dangerous currents']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '60e57ff5-5f9f-4f05-a88b-28065bad47b8'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'How does naming function according to the passage?',
  ARRAY['It was usually negotiated with inhabitants', 'It records existing local usage accurately', 'It overwrites earlier names and spreads through official documents', 'It has little effect outside of cartography']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'a7b1d374-5cb9-4795-a0cf-7d8fd65e2c80'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'What filled unmapped regions on early maps?',
  ARRAY['The names of sponsoring monarchs', 'Warnings written in Latin', 'Grid lines awaiting survey', 'Ornament, invented coastlines and speculative interiors']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0a9c2195-62c6-41fd-a1cc-d9faed130df3'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'What order does the passage describe for a printed name entering common use?',
  ARRAY['Treaties, then schoolbooks, then ordinary speech', 'Ordinary speech, then schoolbooks, then treaties', 'Schoolbooks, then ordinary speech, then treaties', 'Treaties, then ordinary speech, then schoolbooks']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0ae0b9e9-0974-4109-a53c-189aa8697f70'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'The passage calls a blank interior "an invitation". This means it',
  ARRAY['encourages further scientific survey', 'signals that the land is open to be claimed', 'invites correction from local mapmakers', 'suggests the region is dangerous to enter']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'f2f5c547-7722-47e9-ad77-b3e5550190f8'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'Why did previously drawn interiors later appear blank on maps?',
  ARRAY['Printing techniques could not reproduce fine detail', 'Earlier surveys had been proven false', 'Blank space implied the land was unclaimed and available', 'Mapmakers ran short of reliable ink']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c266977e-f286-4be7-ab02-8a7c0c2a872e'::uuid,
  '1706ffc4-a762-4f91-a924-673843a11de4'::uuid,
  'Why does the passage call the distortion durable?',
  ARRAY['Because old maps are rarely re-examined', 'Because treaties cannot be renegotiated', 'Because printed maps outlast manuscripts', 'Because it is structural rather than deliberate']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'The Ship, the Plank, the Self',
  'A ship returns from a long voyage with one rotten plank, which is replaced. It sails again, and another plank is replaced, and over many years every original piece of timber is swapped out. The ship has never been out of service, never been rebuilt, never been renamed. Is it the same ship?

Most people answer yes without much hesitation. Continuity seems to do the work: the changes were gradual, the function unbroken, the crew and the harbour never in any doubt about which vessel they meant.

Then the problem tightens. Suppose someone has been collecting the discarded planks, and assembles them into a ship of their own. Now there are two vessels. One has continuity of form and use; the other has every original component. Both have a serious claim, and they cannot both be the original, because the original was one thing and these are unmistakably two.

The usual instinct is that a fact must exist which settles it, and that we simply lack the information to find it. But there is no further fact hiding anywhere. Every physical detail is already available. What is missing is not evidence but a decision about which criterion of identity we intend to use, and that decision was never made, because ordinary language never needed it. Words are built for the cases we usually encounter, and they fail quietly at the edges rather than announcing that they have run out.

The uncomfortable move is to turn the question on ourselves. The material of a human body is continually replaced. Memories are not stored intact but reconstructed, and they drift a little with each retrieval. Personality shifts across decades, sometimes sharply. The child in an old photograph shares almost no physical matter with the adult holding it, and often disagrees with them about most things worth having an opinion on.

We insist on identity anyway, and we do it for reasons that are largely practical rather than metaphysical. Promises must be kept by someone. Debts must be owed by someone. Punishment and praise both require a stable target. Personal identity may be less a discovery about what we are than a convention we maintain because too much depends on it.

Which does not make it false. Conventions can be indispensable. It only means the question of whether you are the same person who began this passage may not have an answer waiting to be found, but one we have agreed in advance to give.',
  'philosophy'::public.category,
  'expert'::public.difficulty,
  412
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c063cf17-634d-408f-a0a3-65a0a9546e24'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'What is the passage mainly arguing?',
  ARRAY['Identity may be a convention we maintain rather than a fact we discover', 'The ship puzzle has a solution that philosophers have overlooked', 'Memory is the only reliable criterion of selfhood', 'Physical continuity is the true basis of identity']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '5f323871-a736-4cdb-a165-506318365817'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'What complication does the collector of discarded planks introduce?',
  ARRAY['The original ship is proven to be a forgery', 'Two vessels each have a serious claim to being the original', 'The planks turn out to be unusable', 'The crew refuses to sail the repaired ship']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '15841e69-8a42-4349-abf3-9d6707f29e29'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'What reasons does the passage give for why we insist on personal identity?',
  ARRAY['Language has no way to express the alternative', 'Memory proves continuity across time', 'Promises, debts, punishment and praise all need a stable target', 'The body retains most of its original material']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '2dc1ac68-84de-4a15-a50b-169f7d3c7c8f'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'What does the passage say happens to memories over time?',
  ARRAY['They are replaced entirely every few decades', 'They become more accurate as they are rehearsed', 'They are stored intact but become harder to access', 'They are reconstructed and drift with each retrieval']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e1b1dfee-50a6-483c-af62-c4070f412159'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'At what point does the passage say the problem "tightens"?',
  ARRAY['When the discarded planks are assembled into a second ship', 'When the crew changes', 'When the first plank is replaced', 'When the ship is renamed']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '158e0d3a-98a6-4948-ae29-c9a2681bb1a8'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'Words that "fail quietly at the edges" are words that',
  ARRAY['are gradually replaced by technical terms', 'stop being useful in unusual cases without signalling it', 'change meaning between languages', 'lose precision as they become more common']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '1b69be41-bce5-4591-a222-624a3f1aacb7'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'According to the passage, what is actually missing when we cannot settle the question?',
  ARRAY['Physical evidence about the planks', 'Historical records of the voyage', 'A decision about which criterion of identity to use', 'Agreement among philosophers']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'f2d0e8df-6220-4a8d-a9ea-ca97c654eb85'::uuid,
  'bf3cdd5d-062c-4306-ae08-99facb0fcd95'::uuid,
  'Why does the writer insist that calling identity a convention does not make it false?',
  ARRAY['Because no alternative account exists', 'Because most people already believe it', 'Because the physical facts support it anyway', 'Because conventions can still be indispensable']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'The Arrow That Only Points Forward',
  'Almost every fundamental law of physics works equally well in either direction of time. Film two billiard balls colliding, run the film backwards, and nothing in the footage violates mechanics. The reversed collision is a perfectly legal event. The equations do not contain a preference.

Yet the world we inhabit is aggressively one-directional. Cups shatter and never reassemble. Heat flows from the hot object to the cold one and stops there. We remember yesterday and not tomorrow. Something separates the two directions, and it does not appear to be written into the basic laws.

The standard answer is statistical. A system has an enormous number of possible arrangements of its parts, and only a vanishingly small fraction of those arrangements look organised to us. Intact cups occupy a tiny region of that space; scattered fragments occupy an unimaginably larger one. Nothing forbids the fragments from reassembling. It is simply that the arrangements we would call reassembled are so rare, relative to the alternatives, that the probability is indistinguishable from zero across the age of the universe.

This explains why disorder tends to increase going forward. Unfortunately, the same reasoning applies just as well going backwards, since the argument is symmetric in time. Run it in reverse and it predicts that the past should also have been more disordered than the present, which is plainly false. Yesterday was not more chaotic than today.

To break the symmetry, physicists add an assumption rather than a law: that the universe began in an extraordinarily ordered, extremely low-entropy state. Given that starting point, the statistical argument only has room to run in one direction, and the arrow appears. This assumption is usually called the past hypothesis, and it does a remarkable amount of work for something that is essentially a stipulation about initial conditions.

The consequences reach further than thermodynamics. Memory itself depends on the same gradient. Recording a trace of an event requires expending energy and increasing disorder somewhere else, which is possible only in a universe still running down from an ordered beginning. We remember the past rather than the future not because the past is metaphysically fixed and the future open, but because the direction in which entropy increases is the only direction in which records can be made at all.

The arrow of time, on this account, is not a feature of the laws. It is an inheritance from how things happened to start.',
  'science'::public.category,
  'expert'::public.difficulty,
  404
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '79775c0b-a038-4f68-a894-1587418b0f90'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'What is the central claim of the passage?',
  ARRAY['The direction of time comes from the universe''s initial conditions, not the laws', 'Entropy is the most fundamental physical quantity', 'Memory is unreliable because it depends on entropy', 'Time travel is forbidden by thermodynamics']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '6b1cf96f-5422-43ee-a291-47bc64a51032'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'What is unusual about fundamental physical laws with respect to time?',
  ARRAY['They only apply at very large scales', 'They work equally well in either direction', 'They forbid reversed collisions', 'They require a fixed starting point']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'dc003164-ac07-4774-a89d-78024e7e25d4'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'What is the past hypothesis?',
  ARRAY['A proof that time travel is impossible', 'A law derived from thermodynamics', 'An assumption that the universe began in a very low-entropy state', 'A claim that memory is unreliable']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '1dfa76f7-8be6-43f3-a9bb-a899e5578db1'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'What example does the passage use to show the laws have no preferred direction?',
  ARRAY['A star collapsing', 'A shattered cup', 'Heat flowing between objects', 'A filmed collision between billiard balls']::text[],
  3,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '0eebe783-cfb0-4010-a69c-950643802f9b'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'What step do physicists take after the statistical argument proves insufficient?',
  ARRAY['They add an assumption about the initial state of the universe', 'They revise the laws of mechanics', 'They abandon the concept of entropy', 'They treat time as an illusion']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '7d81e48b-c954-4197-ade7-7f2bbae2e5d3'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'Calling the past hypothesis "a stipulation" emphasises that it is',
  ARRAY['a temporary placeholder in the theory', 'something assumed rather than derived', 'a conclusion drawn from observation', 'a mathematical identity']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '6b408108-0b70-4af5-a3d2-68d118b13ba4'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'Why does the statistical explanation alone fail?',
  ARRAY['It contradicts observed collisions', 'It cannot be tested experimentally', 'It applies symmetrically and wrongly predicts a more disordered past', 'It only works for very small systems']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'a098a301-15ca-4715-a14b-974ce8e9b87d'::uuid,
  'f7928cfc-8028-407e-a933-fb87c6efa31c'::uuid,
  'Why do we remember the past rather than the future?',
  ARRAY['Because future events have no physical trace', 'Because the past is metaphysically fixed', 'Because the brain evolved to store completed events', 'Because records can only be made in the direction entropy increases']::text[],
  3,
  'inference'::public.question_type
);

insert into public.passages (id, title, content, category, difficulty, word_count)
values (
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'The Tyranny of the Average',
  'In the late 1940s the United States Air Force had a problem it could not explain. Its pilots were crashing at an alarming rate, and not in combat. The aircraft were inspected and cleared. The pilots were experienced and well trained. Nothing obvious accounted for the accidents.

The cockpits had been designed in the 1920s around the dimensions of the average pilot, calculated from measurements taken at the time. One reasonable hypothesis was that pilots had simply grown larger over the intervening decades, so the Air Force commissioned a fresh study to update the average. More than four thousand pilots were measured across ten dimensions relevant to cockpit fit: height, chest circumference, arm length, and so on.

A young researcher on the project decided to ask a slightly different question first. Rather than computing the new average, he defined a generous band around the existing one, roughly the middle thirty percent of the range on each dimension, and asked how many pilots fell inside that band on all ten measures at once.

The answer was none. Out of more than four thousand men, not a single one was average across all ten dimensions. Even reducing the test to any three dimensions left fewer than five percent qualifying. A pilot with an average arm length would have an unusual chest, or unusually long legs, or a shorter torso. The average pilot, it turned out, was not a rare individual. He did not exist at all.

The design implication was immediate and initially resisted: if nobody is average, then a cockpit fitted to the average fits nobody, and the only workable response is adjustability. Adjustable seats, adjustable pedals, adjustable straps. These are so standard now that their origin is invisible, and performance improved sharply once they arrived.

The statistical lesson generalises badly beyond aviation, which is to say it applies everywhere and is ignored almost everywhere. An average is a summary of a distribution, not a description of any member of it. Averaging across dimensions that vary independently produces a profile that may correspond to no real case. The average customer, the average employee, the average user, and the average student are all constructions of the same kind.

Designing for them is not a neutral simplification. It is designing for someone who is not there, and then wondering why the people who are there keep struggling.',
  'business'::public.category,
  'expert'::public.difficulty,
  394
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'e41003f8-a148-4cdc-a004-c992a04dbc08'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'What is the passage mainly arguing?',
  ARRAY['Designing for an average produces a design that fits no one', 'Statistical studies need larger sample sizes', 'Pilot training mattered more than cockpit fit', 'Aircraft design standards were badly enforced']::text[],
  0,
  'main-idea'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '4f8158d2-9dd1-4f8f-afaf-5f078ae554de'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'How many pilots fell within the average band on all ten dimensions?',
  ARRAY['Roughly one third', 'None', 'Fewer than one hundred', 'About five percent']::text[],
  1,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '8a0ece97-5fbe-4152-a48e-3471315145c4'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'What design response followed from the finding?',
  ARRAY['Recruiting pilots closer to average dimensions', 'Building several fixed cockpit sizes', 'Making cockpit components adjustable', 'Reducing the number of controls']::text[],
  2,
  'detail'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '59e8245a-2e96-41c6-a8de-5cfca0f82a44'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'When had the original cockpits been designed?',
  ARRAY['The 1900s', 'The 1920s', 'The 1940s', 'The 1950s']::text[],
  1,
  'fact'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'c8f3a072-e373-416e-a966-226477978191'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'What did the young researcher do before computing a new average?',
  ARRAY['He asked how many pilots were average on all ten dimensions at once', 'He reviewed the crash reports individually', 'He reduced the study to three dimensions', 'He interviewed pilots about comfort']::text[],
  0,
  'sequence'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  'bb62e2ed-3a39-401f-a2d1-f3bad31b348e'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'Calling a design choice "not a neutral simplification" means it',
  ARRAY['costs more than the alternative', 'has real consequences for the people it excludes', 'is difficult to reverse later', 'requires additional testing']::text[],
  1,
  'vocabulary'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '63a6b7ce-73b2-4030-a6b1-00eb97904f63'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'Why did averaging across ten dimensions produce a profile matching nobody?',
  ARRAY['Pilots had changed since the 1920s', 'The measurements were taken inconsistently', 'The dimensions vary independently of one another', 'The sample was too small to be representative']::text[],
  2,
  'inference'::public.question_type
);

insert into public.questions (id, passage_id, question, options, correct_answer, type)
values (
  '140e573d-7e4c-450d-ac64-dda80bf529ae'::uuid,
  'dfc87b74-2024-4526-a993-8a0a4b4cec47'::uuid,
  'What does the passage imply about phrases like "the average user"?',
  ARRAY['They should be replaced with median figures', 'They are useful shorthand for product teams', 'They describe a typical member of the group', 'They are constructions that may correspond to no real person']::text[],
  3,
  'inference'::public.question_type
);

commit;
