/**
 * Generates supabase/seed.sql from local passage seeds.
 * Run: npx --yes tsx scripts/generate-seed.ts
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { passages } from '../src/data/passages/index.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'supabase', 'seed.sql');

function joinParagraphs(paragraphs: string[]): string {
  return paragraphs.map((paragraph) => paragraph.trim()).filter(Boolean).join('\n\n');
}

/** Deterministic UUID from a slug so re-seeding is stable. */
function uuidFromSlug(slug: string): string {
  const hash = createHash('sha256').update(`readittwin:${slug}`).digest('hex');
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    `4${hash.slice(13, 16)}`,
    `a${hash.slice(17, 20)}`,
    hash.slice(20, 32),
  ].join('-');
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(options: string[]): string {
  return `ARRAY[${options.map(sqlString).join(', ')}]::text[]`;
}

const lines: string[] = [
  '-- Seed passages + questions from local original content.',
  '-- Generated by scripts/generate-seed.ts — do not hand-edit; regenerate instead.',
  '-- Requires migration 20260906153610_phase06_foundation.sql applied first.',
  '',
  'begin;',
  '',
  'delete from public.questions;',
  'delete from public.passages;',
  '',
];

for (const passage of passages) {
  const passageId = uuidFromSlug(passage.id);
  const content = joinParagraphs(passage.paragraphs);

  lines.push(
    `insert into public.passages (id, title, content, category, difficulty, word_count)`,
    `values (`,
    `  ${sqlString(passageId)}::uuid,`,
    `  ${sqlString(passage.title)},`,
    `  ${sqlString(content)},`,
    `  ${sqlString(passage.category)}::public.category,`,
    `  ${sqlString(passage.difficulty)}::public.difficulty,`,
    `  ${passage.wordCount}`,
    `);`,
    '',
  );

  for (const question of passage.questions) {
    const questionId = uuidFromSlug(question.id);
    lines.push(
      `insert into public.questions (id, passage_id, question, options, correct_answer, type)`,
      `values (`,
      `  ${sqlString(questionId)}::uuid,`,
      `  ${sqlString(passageId)}::uuid,`,
      `  ${sqlString(question.prompt)},`,
      `  ${sqlTextArray(question.options)},`,
      `  ${question.answerIndex},`,
      `  ${sqlString(question.type)}::public.question_type`,
      `);`,
      '',
    );
  }
}

lines.push('commit;', '');

writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`Wrote ${outPath} (${passages.length} passages)`);
